name: Coverage

on: [ push ]

jobs:
  build:
    name: Coverage 📊
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize Node
      uses: actions/setup-node@v3
      with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

    - name: Install deps
      run: npm ci

    - name: Run coverage
      run: npm run coverage